# Generated by Django 2.2.2 on 2024-05-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='Device API Key', max_length=30)),
                ('pin', models.CharField(help_text='PIN value from V0 to V50', max_length=3)),
                ('name', models.CharField(help_text='Device name', max_length=30)),
                ('value', models.CharField(default='0', help_text='Value of the sensor', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Publish Date')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
