# Generated by Django 4.2.2 on 2024-05-25 13:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hengio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hengio',
            name='days_of_week',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=[0, 1, 2, 3, 4, 5, 6], help_text='Days of the week when the event should trigger', max_length=13),
        ),
    ]
