# Generated by Django 4.2.2 on 2024-05-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hengio', '0002_alter_hengio_days_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hengio',
            name='status',
            field=models.IntegerField(choices=[(1, 'On'), (2, 'Off')], default=1, help_text='Value of the sensor'),
        ),
    ]
