# Generated by Django 4.2.13 on 2024-05-26 06:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hengio', '0003_alter_hengio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hengio',
            name='days_of_week',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Hai'), (1, 'Ba'), (2, 'Tư'), (3, 'Năm'), (4, 'Sáu'), (5, 'Bảy'), (6, 'Chủ Nhật')], default=[0, 1, 2, 3, 4, 5, 6], help_text='Days of the week when the event should trigger', max_length=13),
        ),
    ]
