# Generated by Django 4.2.2 on 2024-05-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setnguong', '0002_alter_setnguong_compare_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setnguong',
            name='compare_value',
            field=models.CharField(help_text='Compare value', max_length=3),
        ),
    ]
