# Generated by Django 4.2.13 on 2024-05-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='pump_choise',
        ),
        migrations.AddField(
            model_name='auto',
            name='pump_choice',
            field=models.IntegerField(choices=[(1, 'Cozantinuous Mode (Always On)'), (2, 'Interval Mode (On for 5s, Off for 5s)')], default=1, help_text='Type'),
        ),
    ]
