# Generated by Django 4.2.13 on 2024-05-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_remove_auto_pump_choise_auto_pump_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='api_key',
            field=models.CharField(default='TEY8OO5iafAV96gRKcZohbO6ED', help_text='Device API Key', max_length=30),
        ),
    ]
